# Use an official Node runtime as a parent image
FROM node:18.13 as builder

# Set the working directory to /app
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install Angular CLI globally
RUN npm install -g @angular/cli

# Install app dependencies
RUN npm install

# Copy the current directory contents into the container at /app
COPY . .

# Build the Angular app
RUN ng build --configuration=production --output-path=/app/dist

# Use an official Nginx runtime as a parent image
FROM nginx:alpine

# Remove default Nginx website
RUN rm -rf /usr/share/nginx/html/*


# Copy the Angular build from the builder stage to the NGINX html directory
COPY --from=builder /app/dist /usr/share/nginx/html

# Expose port 4200
EXPOSE 4200

# Start NGINX
CMD ["nginx", "-g", "daemon off;"]
